In [7]:
import numpy as np
arr=np.array([2,1,3,4,5])
arr

array([2, 1, 3, 4, 5])

In [2]:
import numpy as np
arr=[2,1,3,4,5]
np.array(arr)

array([2, 1, 3, 4, 5])

a=[]
n=int(input('enter the size of array:'))
for i in range (n):
    val=int(input('enter the value'))
    a.append(val)
arr=np.array(a)
arr
for i in range(val):
    print(arr[1])

In [33]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
b=np.array([[1,2,3,6],[4,5,6.5],[7,8,9,11]])
b


C:\Users\HP\AppData\Local\Temp\ipykernel_12240\4292297641.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[1,2,3,6],[4,5,6.5],[7,8,9,11]])


array([list([1, 2, 3, 6]), list([4, 5, 6.5]), list([7, 8, 9, 11])],
      dtype=object)

In [21]:
a1=b.reshape(5,2)
a1

ValueError: cannot reshape array of size 3 into shape (5,2)

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
arr=np.random.randint(1,10,5)
arr

array([9, 5, 2, 9, 6])

In [27]:
np.random.rand(5,3)

array([[0.93217611, 0.34790055, 0.31667305],
       [0.34076016, 0.44097119, 0.37249103],
       [0.80077974, 0.65225536, 0.15711157],
       [0.22616597, 0.62107027, 0.04379802],
       [0.61203408, 0.58196984, 0.66021701]])

In [48]:
np.random.seed(12)
a=np.random.randn(5,3)
a
arr1=a[2:]
arr1

array([[ 0.00512708, -0.12022767, -0.80698188],
       [ 2.87181939, -0.59782292,  0.47245699],
       [ 1.09595612, -1.2151688 ,  1.34235637]])

In [29]:
np.random.seed(125)
arr=np.random.randint(1,100,12)
arr
a1=arr.reshape(3,4)
a1
b1=a1.reshape(12)
b1

array([62, 30, 99, 88, 68, 78, 87, 44, 60, 65, 38, 87])

In [32]:
matrix=[]
row=int(input('enter row no.'))
col=int(input('enter column no.'))
for i in range(row):
    a=[]
    for j in range (col):
        val=int(input('enter value'))
        a.append(val)
        matrix.append(a)
        for i in range(row):
            for j in range(col):
                print(arr[i][j],end='')
                print()
        

enter row no.3
enter column no.1
enter value2


IndexError: invalid index to scalar variable.

In [35]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
b=a[2,1]
b

8

In [45]:
a=np.array([10,20,30,40,50,60,70])
b=a[3:6].copy()
b
b[:]=1
a

array([10, 20, 30, 40, 50, 60, 70])

In [52]:
arr=np.arange(1,16)
arr
b=arr[arr%2==0]=6
b
arr

array([ 1,  6,  3,  6,  5,  6,  7,  6,  9,  6, 11,  6, 13,  6, 15])

In [55]:
a=np.arange(1,6)
a
b=a+2
b

array([3, 4, 5, 6, 7])

In [59]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)
c=a+b
c

array([[ 6,  8],
       [10, 12]])

In [61]:
a=np.array([10,20,30,40,50,60,70])
a
np.min(a)

10

In [67]:
np.linspace(1.2,.5,7)

array([1.2       , 1.08333333, 0.96666667, 0.85      , 0.73333333,
       0.61666667, 0.5       ])

In [70]:
np.random.seed(112)
a=np.random.randint(1,21,9).reshape(3,3)
a


array([[ 5, 12,  9],
       [ 2,  6, 13],
       [ 8,  9, 10]])

In [71]:
b=np.sum(a,axis=1)
b

array([26, 21, 27])